import type { Metadata } from 'next';
import { type LayoutProps } from '@/types/root';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'ERP CRM',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
