#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
if [ $? -ne 0 ]; then
	echo "Linting failed. Please fix the issues before committing."
	exit 1
fi
echo "Linting passed."
echo "Proceeding with commit..."